# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rover.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\"\x0c\n\nMapRequest\"\x1f\n\x0bMapResponse\x12\x10\n\x08map_data\x18\x01 \x03(\t\"&\n\x0e\x43ommandRequest\x12\x14\n\x0crover_number\x18\x01 \x01(\x05\"#\n\x0f\x43ommandResponse\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"\x19\n\x17MineSerialNumberRequest\"-\n\x18MineSerialNumberResponse\x12\x11\n\tmine_data\x18\x01 \x03(\t\",\n\x0eMinePinRequest\x12\x1a\n\x12mine_serial_number\x18\x01 \x01(\t\"#\n\x0fMinePinResponse\x12\x10\n\x08mine_pin\x18\x01 \x01(\t\"%\n\rStatusRequest\x12\x14\n\x0crover_number\x18\x01 \x01(\x05\"2\n\x17\x45xecutionStatusResponse\x12\x17\n\x0fstatus_received\x18\x01 \x01(\x08\x32\xb1\x02\n\x0cRoverControl\x12%\n\x06GetMap\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12\x32\n\x0bGetCommands\x12\x0f.CommandRequest\x1a\x10.CommandResponse\"\x00\x12L\n\x13GetMineSerialNumber\x12\x18.MineSerialNumberRequest\x1a\x19.MineSerialNumberResponse\"\x00\x12\x33\n\x0cShareMinePin\x12\x0f.MinePinRequest\x1a\x10.MinePinResponse\"\x00\x12\x43\n\x15NotifyExecutionStatus\x12\x0e.StatusRequest\x1a\x18.ExecutionStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=15
  _globals['_MAPREQUEST']._serialized_end=27
  _globals['_MAPRESPONSE']._serialized_start=29
  _globals['_MAPRESPONSE']._serialized_end=60
  _globals['_COMMANDREQUEST']._serialized_start=62
  _globals['_COMMANDREQUEST']._serialized_end=100
  _globals['_COMMANDRESPONSE']._serialized_start=102
  _globals['_COMMANDRESPONSE']._serialized_end=137
  _globals['_MINESERIALNUMBERREQUEST']._serialized_start=139
  _globals['_MINESERIALNUMBERREQUEST']._serialized_end=164
  _globals['_MINESERIALNUMBERRESPONSE']._serialized_start=166
  _globals['_MINESERIALNUMBERRESPONSE']._serialized_end=211
  _globals['_MINEPINREQUEST']._serialized_start=213
  _globals['_MINEPINREQUEST']._serialized_end=257
  _globals['_MINEPINRESPONSE']._serialized_start=259
  _globals['_MINEPINRESPONSE']._serialized_end=294
  _globals['_STATUSREQUEST']._serialized_start=296
  _globals['_STATUSREQUEST']._serialized_end=333
  _globals['_EXECUTIONSTATUSRESPONSE']._serialized_start=335
  _globals['_EXECUTIONSTATUSRESPONSE']._serialized_end=385
  _globals['_ROVERCONTROL']._serialized_start=388
  _globals['_ROVERCONTROL']._serialized_end=693
# @@protoc_insertion_point(module_scope)
