# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rover_pb2 as rover__pb2


class RoverControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/RoverControl/GetMap',
                request_serializer=rover__pb2.MapRequest.SerializeToString,
                response_deserializer=rover__pb2.MapResponse.FromString,
                )
        self.GetCommands = channel.unary_unary(
                '/RoverControl/GetCommands',
                request_serializer=rover__pb2.CommandRequest.SerializeToString,
                response_deserializer=rover__pb2.CommandResponse.FromString,
                )
        self.GetMineSerialNumber = channel.unary_unary(
                '/RoverControl/GetMineSerialNumber',
                request_serializer=rover__pb2.MineSerialNumberRequest.SerializeToString,
                response_deserializer=rover__pb2.MineSerialNumberResponse.FromString,
                )
        self.ShareMinePin = channel.unary_unary(
                '/RoverControl/ShareMinePin',
                request_serializer=rover__pb2.MinePinRequest.SerializeToString,
                response_deserializer=rover__pb2.MinePinResponse.FromString,
                )
        self.NotifyExecutionStatus = channel.unary_unary(
                '/RoverControl/NotifyExecutionStatus',
                request_serializer=rover__pb2.StatusRequest.SerializeToString,
                response_deserializer=rover__pb2.ExecutionStatusResponse.FromString,
                )


class RoverControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyExecutionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.MapRequest.FromString,
                    response_serializer=rover__pb2.MapResponse.SerializeToString,
            ),
            'GetCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommands,
                    request_deserializer=rover__pb2.CommandRequest.FromString,
                    response_serializer=rover__pb2.CommandResponse.SerializeToString,
            ),
            'GetMineSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerialNumber,
                    request_deserializer=rover__pb2.MineSerialNumberRequest.FromString,
                    response_serializer=rover__pb2.MineSerialNumberResponse.SerializeToString,
            ),
            'ShareMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePin,
                    request_deserializer=rover__pb2.MinePinRequest.FromString,
                    response_serializer=rover__pb2.MinePinResponse.SerializeToString,
            ),
            'NotifyExecutionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyExecutionStatus,
                    request_deserializer=rover__pb2.StatusRequest.FromString,
                    response_serializer=rover__pb2.ExecutionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoverControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoverControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverControl/GetMap',
            rover__pb2.MapRequest.SerializeToString,
            rover__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverControl/GetCommands',
            rover__pb2.CommandRequest.SerializeToString,
            rover__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMineSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverControl/GetMineSerialNumber',
            rover__pb2.MineSerialNumberRequest.SerializeToString,
            rover__pb2.MineSerialNumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShareMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverControl/ShareMinePin',
            rover__pb2.MinePinRequest.SerializeToString,
            rover__pb2.MinePinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyExecutionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverControl/NotifyExecutionStatus',
            rover__pb2.StatusRequest.SerializeToString,
            rover__pb2.ExecutionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
